AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'app/channels/**/*'
    - 'config.ru'
    - 'app/models/application_record.rb'
Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/serializers/*'
    - 'app/controllers/**/*'
    - 'app/serializers/*'
    - 'spec/support/request_helpers.rb'
    - 'spec/support/*'
    - 'app/uploaders/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
